export const products = [
  {
    supplierId: 'SUPPLIER001',
    title: 'High Garden Pinot Noir 2021',
    skuCode: 'HGVPIN216',
    brand: 'High Garden',
    categoryId: 'Alcoholic Beverage',
    subCategoryId: 'Wine',
    segmentId: 'Red',
    globalWholesalePrice: 279.06,
  },
  {
    supplierId: 'SUPPLIER001',
    title: 'Koyama Methode Brut Nature NV',
    skuCode: 'KOYBRUNV6',
    brand: 'Koyama Wines',
    categoryId: 'Alcoholic Beverage',
    subCategoryId: 'Wine',
    segmentId: 'Sparkling',
    globalWholesalePrice: 120.0,
  },
  {
    supplierId: 'SUPPLIER001',
    title: 'Koyama Riesling 2018',
    skuCode: 'KOYNR1837',
    brand: 'Koyama Wines',
    categoryId: 'Alcoholic Beverage',
    subCategoryId: 'Wine',
    segmentId: 'Port/Dessert',
    globalWholesalePrice: 215.04,
  },
  {
    supplierId: 'SUPPLIER001',
    title: 'Koyama Tussock Riesling 2019',
    skuCode: 'KOYRIE19',
    brand: 'Koyama Wines',
    categoryId: 'Alcoholic Beverage',
    subCategoryId: 'Wine',
    segmentId: 'White',
    globalWholesalePrice: 215.04,
  },
  {
    supplierId: 'SUPPLIER001',
    title: 'Lacourte-Godbillon Brut Cru NV',
    skuCode: 'LACBNATNV6',
    brand: 'Lacourte-Godbillon',
    categoryId: 'Alcoholic Beverage',
    subCategoryId: 'Wine',
    segmentId: 'Sparkling',
    globalWholesalePrice: 409.32,
  },
  {
    supplierId: 'SUPPLIER002',
    title: 'The Macallan Double Cask 12 Year Old',
    skuCode: 'MAC12DC70',
    brand: 'The Macallan',
    categoryId: 'Alcoholic Beverage',
    subCategoryId: 'Whisky',
    segmentId: 'Single Malt',
    globalWholesalePrice: 325.0,
  },
  {
    supplierId: 'SUPPLIER002',
    title: 'Glenfiddich 18 Year Old',
    skuCode: 'GLENF18YO70',
    brand: 'Glenfiddich',
    categoryId: 'Alcoholic Beverage',
    subCategoryId: 'Whisky',
    segmentId: 'Single Malt',
    globalWholesalePrice: 280.0,
  },
  {
    supplierId: 'SUPPLIER002',
    title: 'Lagavulin 16 Year Old',
    skuCode: 'LAGA16YO70',
    brand: 'Lagavulin',
    categoryId: 'Alcoholic Beverage',
    subCategoryId: 'Whisky',
    segmentId: 'Single Malt',
    globalWholesalePrice: 450.0,
  },
];

export const pricingProfiles = [];
